### ISSUE TITLE
好像无法解析了

### ISSUE THREAD

**Issue by ICLXL** [Rhilip/doubanSearchCrack#10]
douban-search-crack\dist\index.js:16
    throw new Error("Can't find __DATA__ field from input.");
          ^

Error: Can't find __DATA__ field from input.

**Comment by Rhilip** [comment]
目前(2024.11.08) 豆瓣没有对`__DATA__` 字段进行加密，直接就可以取了
![image](https://github.com/user-attachments/assets/6559aaf8-d308-4d26-b93e-14654370f11a)
